FROM debian:stable-slim

ENV LANG=C.UTF-8

RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "APT::Install-Recommends "0" ; APT::Install-Suggests "0" ;" > /etc/apt/apt.conf.d/default \
    && apt update  \
    && apt upgrade -y \
    && apt install -y pipx \
    && pipx install --include-deps ansible \
    && pipx inject ansible argcomplete \
    && apt autoremove --purge -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/* 